// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbq3y4h5gNI-DT76VkxN1qp-6ngtIEam4',
    appId: '1:624722495028:web:9c779a444b7e33d6682c61',
    messagingSenderId: '624722495028',
    projectId: 'loginui-44026',
    authDomain: 'loginui-44026.firebaseapp.com',
    storageBucket: 'loginui-44026.firebasestorage.app',
    measurementId: 'G-J5131JX339',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1YToCztoVemGJSgrsx6q9RCHFAuin1h8',
    appId: '1:624722495028:android:1b1277ff809d615c682c61',
    messagingSenderId: '624722495028',
    projectId: 'loginui-44026',
    storageBucket: 'loginui-44026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATc1zA1UmULpbReSQjyrNMpYA4simhm50',
    appId: '1:624722495028:ios:f075ac8e3bd7fd62682c61',
    messagingSenderId: '624722495028',
    projectId: 'loginui-44026',
    storageBucket: 'loginui-44026.firebasestorage.app',
    iosClientId:
        '624722495028-if3iergf7i01f7mp9pg1qemq1hbrm3g9.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCoomerceFruit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATc1zA1UmULpbReSQjyrNMpYA4simhm50',
    appId: '1:624722495028:ios:f075ac8e3bd7fd62682c61',
    messagingSenderId: '624722495028',
    projectId: 'loginui-44026',
    storageBucket: 'loginui-44026.firebasestorage.app',
    iosClientId:
        '624722495028-if3iergf7i01f7mp9pg1qemq1hbrm3g9.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCoomerceFruit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbq3y4h5gNI-DT76VkxN1qp-6ngtIEam4',
    appId: '1:624722495028:web:c517b80d3f350dbe682c61',
    messagingSenderId: '624722495028',
    projectId: 'loginui-44026',
    authDomain: 'loginui-44026.firebaseapp.com',
    storageBucket: 'loginui-44026.firebasestorage.app',
    measurementId: 'G-88CP4QV5PE',
  );
}
