// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANFoArjI2vlHzSeGBjCrm1OkJSMrPRhC4',
    appId: '1:649071935690:web:3885ff69ef154160747433',
    messagingSenderId: '649071935690',
    projectId: 'fruit-hub-dd0b2',
    authDomain: 'fruit-hub-dd0b2.firebaseapp.com',
    storageBucket: 'fruit-hub-dd0b2.firebasestorage.app',
    measurementId: 'G-Z01CMP6S77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC85ZRA8acN6iV7QEw0r23ZOG8gq9mvtwo',
    appId: '1:649071935690:android:26136ff295dfdb23747433',
    messagingSenderId: '649071935690',
    projectId: 'fruit-hub-dd0b2',
    storageBucket: 'fruit-hub-dd0b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEzp9PaALe6g0rVsqC3zH5jSX2bYSfz2w',
    appId: '1:649071935690:ios:612c42f0ae489488747433',
    messagingSenderId: '649071935690',
    projectId: 'fruit-hub-dd0b2',
    storageBucket: 'fruit-hub-dd0b2.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEzp9PaALe6g0rVsqC3zH5jSX2bYSfz2w',
    appId: '1:649071935690:ios:612c42f0ae489488747433',
    messagingSenderId: '649071935690',
    projectId: 'fruit-hub-dd0b2',
    storageBucket: 'fruit-hub-dd0b2.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANFoArjI2vlHzSeGBjCrm1OkJSMrPRhC4',
    appId: '1:649071935690:web:6e219047dbd1b2cb747433',
    messagingSenderId: '649071935690',
    projectId: 'fruit-hub-dd0b2',
    authDomain: 'fruit-hub-dd0b2.firebaseapp.com',
    storageBucket: 'fruit-hub-dd0b2.firebasestorage.app',
    measurementId: 'G-1BKP8YZZ1Z',
  );
}
